### ISSUE TITLE
[BUG] Error getting initial buttons

### ISSUE THREAD

**Issue by Seversonic** [jamesread/OliveTin#4]
**Describe the bug**
Error getting initial buttons is displayed when opening the web ui.
TypeError: NetworkError when attempting to fetch resource.

**To Reproduce**
Build with docker-compose
```
version: "2.1"
services:
  airsonic:
    image: jamesread/olivetin
    container_name: olivetin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/
    volumes:
      - /olivetin:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.olivetin.rule=Host(`olivetin.example.com`)"
      - "traefik.http.routers.olivetin.entrypoints=websecure"
      - "traefik.http.routers.olivetin.tls=true"
      # Uncomment to fetch Let's Encrypt certificates.
      # Make sure you set up DNS records and they point to your IP.
      - "traefik.http.routers.olivetin.tls.certresolver=letsencrypt"

networks:
  default:
    external:
      name: traefik_default



```

**Expected behavior**
Page should launch with 1 button as per the config.yaml

**Screenshots**
![image](https://user-images.githubusercontent.com/43625790/118893590-e11d7300-b8bf-11eb-9847-f2b20dc38317.png)

**Comment by ksurl** [comment]
getting same issue here with a similar compose file

```
version: "3.8"
services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    networks:
      - <NET>
    volumes:
      - /docker/olivetin:/config:ro
    restart: unless-stopped

networks:
  <NET>:
    external:
      name: <NET>
```

btw @Seversonic, your environment variables don't do anything. the Dockerfile doesn't have any reference to respecting UID/GID or timezone. it's currently hardcoded to user 1001.

**Comment by jamesread** [comment]
Hey @Seversonic, @ksurl . Thanks for giving this project a try, and sorry that you're running into issues. I'd like to help. 

I've not tried with `docker compose` (I use `podman` for everything), but I'll spin up a test machine now and try to re-produce. 

Typically, a `NetworkError` and "Error getting initial buttons" would mean that the webui Javascript cannot get to port 1338 (the REST API) on the container. If you know how to open your browser's Web Developer tools, and take a look at the Network tab when loading the page, it might provide a bit more debug info that would be helpful. It's probably "connection refused" or similar.  Port 1339 (gRPC)

> the Dockerfile doesn't have any reference to respecting UID/GID or timezone. it's currently hardcoded to user 1001.

Ah, this is typically how I build all my Dockerfiles from working with Kubernetes. These can be overridden with `-u` when running with `podman`, but does Docker [compose] prefer to use variables? Happy to change the `Dockerfile` user if needed.

**Comment by ksurl** [comment]
leaving it to the user option in docker or compose is fine.

I will fiddle with the IP it's listening on. I tried 0.0.0.0 and 127.0.0.1 and localhost for all the api and gRPC (the webui obviously left on 0.0.0.0 so it can be published on 1337 to the host). and also leaving it commented out of the config so it uses default settings.

here is what I get from the browser console:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://0.0.0.0:1338/GetButtons. (Reason: CORS request did not succeed).`

**Comment by jamesread** [comment]
I've just been playing around with my setup using haproxy... and I realize I have a bit of a design problem here!

The webui is basically told where the OliveTin API is listening from the golang daemon - so when the webui loads, it also gets "The REST API is running on port X". However, the value it uses is just whatever the addres+port the REST server is listening on (eg, 192.168.0.4:1338).

If you're running behind a proxy, the webui is not likely to be able to get to 192.168.0.4 (because it's behind a proxy - haproxy/traefik/whatever). 

I think the most common fix for this sort of thing is having another config.yaml option for `externalApiAddress` (so you would have olivetin.example.com - which points to port 1337 and olivetin-api.example.com - which points to port 1338). If I made that change, @ksurl , @Seversonic , would that work for you?

**Comment by ksurl** [comment]
I am getting the same error whether I access it directly on the host IP such as http://192.168.0.4:1337 or https://olivetin.example.com behind my nginx reverse proxy. here is another message before the cross origin error: 
```
Error fetch-initial-buttons:  TypeError: NetworkError when attempting to fetch resource. main.js:6:11
    showBigError http://192.168.0.4:1337/main.js:6
    onInitialLoad http://192.168.0.4:1337/main.js:26
    (Async: promise callback)
    onInitialLoad http://192.168.0.4:1337/main.js:25
    <anonymous> http://192.168.0.4:1337/main.js:33
    (Async: promise callback)
    <anonymous> http://192.168.0.4:1337/main.js:32
```

**Comment by ksurl** [comment]
I see so you would need 2 entries in your proxy config. I think your suggestion would work, but it seems odd it can't find itself on the same container its running in without leaving the container to hit the proxied subdomain. I wonder why it isn't an issue on podman (is it not?)

**Comment by Seversonic** [comment]
I'm unfortunately not a wizard when it comes to web dev and docker. 

One thing I still have to try is to try and create the container from scratch again. On my initial container start I did not have the config.yaml file in place and it wouldn't boot. I've run into similar issues with other containers. 

I did set the log level to debug, but it didn't flag anything strange. 

```
time="2021-05-19T16:28:20-06:00" level=info msg="OliveTin initializing"


time="2021-05-19T16:28:20-06:00" level=info msg="OliveTin started" listenAddressGrpcActions="0.0.0.0:1339" listenAddressRestActions="0.0.0.0:1338" listenAddressWebUI="0.0.0.0:1337"


time="2021-05-19T16:28:20-06:00" level=debug msg="&{ListenAddressWebUI:0.0.0.0:1337 ListenAddressRestActions:0.0.0.0:1338 ListenAddressGrpcActions:0.0.0.0:1339 LogLevel:DEBUG ActionButtons:[{Title:Restart Plex Icon:smile Shell:docker restart plex CSS:map[] Timeout:0}] Entities:[]}"


time="2021-05-19T16:28:20-06:00" level=info msg="Found the webui directory here: /var/www/olivetin/"

```

**Comment by ksurl** [comment]
for the error: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://0.0.0.0:1338/GetButtons. (Reason: CORS request did not succeed).`

does this help?

https://web.dev/cross-origin-resource-sharing/
https://flaviocopes.com/golang-enable-cors/

**Comment by ksurl** [comment]
for the other error: failed to fetch initial buttons, basically I think the issue is that since I am running the container on a server and accessing the web ui from my desktop, whatever IP it is binding to is not going to match the host IP of the server so it can't find the files that are being served. localhost, 127.0.0.1 or the docker bridge network or custom network IP wouldn't be reachable from another device other than the host and since it's a cli only install, there's no local browser I can use to test it.

**Comment by jamesread** [comment]
Hey there, I know what's up and I've got a plan to fix it - thanks so much for your patience. Just work, and stuff has been busy. Hoping to make a new release over the weekend, thanks!

**Comment by ksurl** [comment]
Thanks for working on it. I wasn't expecting a quick fix so take your time.

**Comment by jamesread** [comment]
Hey @ksurl , @Seversonic - thanks for your patience. I've just put out a new release that *hopefully* should fix this. The fix was technically kind of simple, but it needed quite a few changes, and it's a bit tricky to test. 

The fix is that the API and the WebUI are now accessible on the same port (api is at `/api/`). This ellimintes a whole bunch of CORS annoying stuff, and means that only one port (1337) needs to be open, and 1 route in your reverse proxy configuration.

Could you try the 2021-05-24 release and let me know if it works for you now?

**Comment by Seversonic** [comment]
Hey James, 

Just tried the new container, cleared my cache but I'm still getting the same errors. 


![image](https://user-images.githubusercontent.com/43625790/119412901-dee55b00-bca9-11eb-8834-aa5992999bca.png)


Let me know if you need more details. 

My debug log showed the same as previously posted.

**Comment by jamesread** [comment]
Hey @Seversonic. Oh no! :-( 

The web developer view screenshot you posted is super helpful. It seems to be trying to go to 0.0.0.0 still, which is what the old version was doing when behind a proxy. 

I did some double checking, and HTTPS *should* work, but I didn't personally test it. I don't think it's causing the problem here. 

It seems to me like it could be running the old version still. Would you mind posting me the first 10 lines or so of your startup log after restarting the container? The log messages changed in this new version so we can see if the container really is being used. The first message should be "OliveTin initializing".

**Comment by Seversonic** [comment]
I tried a couple different browsers, forced reloads, cleared caches but still the same thing. 

I purged my container images so it should be grabbing the latest from docker hub unless I need special tag?

Is there a location in the filesystem to see the correct version?

I'm grabbing the logs via the portainer interface, but is there a location in the file system I should be grabbing them from? (not familiar with go)

Logs
```
time="2021-05-24T16:52:18-06:00" level=info msg="OliveTin initializing",
time="2021-05-24T16:52:18-06:00" level=info msg="OliveTin started" listenAddressGrpcActions="0.0.0.0:1339" listenAddressRestActions="0.0.0.0:1338" listenAddressWebUI="0.0.0.0:1337",
time="2021-05-24T16:52:18-06:00" level=debug msg="&{ListenAddressWebUI:0.0.0.0:1337 ListenAddressRestActions:0.0.0.0:1338 ListenAddressGrpcActions:0.0.0.0:1339 LogLevel:DEBUG ActionButtons:[{Title:Restart Plex Icon:smile Shell:docker restart plex CSS:map[] Timeout:0}] Entities:[]}",
time="2021-05-24T16:52:18-06:00" level=info msg="Found the webui directory here: /var/www/olivetin/",
time="2021-05-24T16:56:00-06:00" level=debug msg="Adding CORS header origin: https://olivetin.example.com",
time="2021-05-24T16:56:00-06:00" level=debug msg="Adding CORS header origin: https://olivetin.example.com",
time="2021-05-24T16:56:00-06:00" level=debug msg="Adding CORS header origin: https://olivetin.example.com",
```

**Comment by Seversonic** [comment]
Apologies:  I was pulling the default container. I specified `olivetin:20210524` and it pulled the newer version. 


Getting a 404 page now
```
ime="2021-05-24T17:09:07-06:00" level=info msg="OliveTin initializing"
time="2021-05-24T17:09:07-06:00" level=info msg="OliveTin started"
time="2021-05-24T17:09:07-06:00" level=debug msg="&{UseSingleHTTPFrontend:true ListenAddressSingleHTTPFrontend:0.0.0.0:1337 ListenAddressWebUI:0.0.0.0:1337 ListenAddressRestActions:localhost:1338 ListenAddressGrpcActions:localhost:1339 ExternalRestAddress: LogLevel:DEBUG ActionButtons:[{Title:Restart Plex Icon:smile Shell:docker restart plex CSS:map[] Timeout:0}] Entities:[]}"
time="2021-05-24T17:09:07-06:00" level=info msg="Starting single HTTP frontend" address="0.0.0.0:1337"
time="2021-05-24T17:09:07-06:00" level=info msg="Starting REST API" address="localhost:1339"
time="2021-05-24T17:09:07-06:00" level=info msg="Starting WebUI server" address="0.0.0.0:1337"
time="2021-05-24T17:09:07-06:00" level=info msg="Found the webui directory here: /var/www/olivetin/"
time="2021-05-24T17:09:07-06:00" level=fatal msg="listen tcp 0.0.0.0:1337: bind: address already in use"
```

**Comment by ksurl** [comment]
seems to work for me. here is my compose file for reference:

```
version: "3.8"
services:
  olivetin:
    image: jamesread/olivetin:20210524
    container_name: olivetin
    networks:
      - proxy
    volumes:
      - /docker/olivetin:/config:ro
    ports:
      - 1337:1337
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy

```

**Comment by jamesread** [comment]
@ksurl Great!

@Seversonic - we're getting there!

I didn't push the last Docker image with the "latest" tag - so I'll remember to do that in future, thank you. When you specified the exact version it worked.

So, to fix your problem - I assume you just want 1 port open for OliveTin, which is going to be the default going forward. Can you *delete* the following lines from your config.yaml and restart the container?; 

```
listenAddressWebUI:0.0.0.0:1338 
listenAddressRestActions:localhost:1338
listenAddressGrpcActions:localhost:1339 
`

This means that OliveTin should just use defaults and listen on port 1337 externally, with all the other addresses being internal to the container (localhost).

If you still have problems then, could you include the following;

1. Your config.yaml (don't need any `actions:` stuff)
2. The first few lines of your OliveTin startup log
3. A screenshot of the console and network tab from the WebDeveloper view

Thank you for your patience :) I am making changes in the next version to make some of this easier (like including the version number in the startup log, etc), so your pain and problems won't affect other people!

**Comment by Seversonic** [comment]
Commented out the top line in the 'config.yaml' and it works like a charm!
Config now only contains the logLevel and actions. 

Thank you so much for the app and help. Really looking forward to utilizing this!

**Comment by AlphaJack** [comment]
@jamesread can you please implement an option so we can prepend a custom path to `/api/`? For Instance if I'm hosting OliveTin under `/olivetin/` I'd like to have APIs under `/olivetin/api/` instead of just `/api/`.

This is my workaround at the moment:

```nginx
location /olivetin/ {
 proxy_pass http://127.0.0.1:1337/;
}

location ~ ^(/api/GetDashboardComponents|/api/GetLogs|/api/StartAction|/api/ValidateArgumentType)$ {
 proxy_pass http://127.0.0.1:1338;
}
```
